# Generated by Django 5.2.14 on 2026-05-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Videojuego",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("ACC", "Acción"),
                            ("AVT", "Aventura"),
                            ("RPG", "Rol (RPG)"),
                            ("EST", "Estrategia"),
                            ("DEP", "Deportes"),
                            ("SIM", "Simulación"),
                        ],
                        default="ACC",
                        max_length=3,
                    ),
                ),
                ("desarrollador", models.CharField(max_length=100)),
                ("fecha_lanzamiento", models.DateField()),
                ("imagen_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
