# Generated by Django 5.2.14 on 2026-05-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videojuego",
            name="imagen_url",
        ),
        migrations.AddField(
            model_name="videojuego",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="videojuegos/"),
        ),
        migrations.AddField(
            model_name="videojuego",
            name="imagen_url_externa",
            field=models.URLField(
                blank=True,
                help_text="URL alternativa si no hay imagen local",
                null=True,
            ),
        ),
    ]
