# Generated by Django 5.2.14 on 2026-05-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_videojuego_created_at_videojuego_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='genero',
            field=models.CharField(choices=[('ACC', 'Accion'), ('AVT', 'Aventura'), ('RPG', 'Rol (RPG)'), ('EST', 'Estrategia'), ('DEP', 'Deportes'), ('SIM', 'Simulacion')], default='ACC', max_length=3),
        ),
    ]
